// Stamps the footer application version (yy.mm.dd.hhmm) using UTC date/time.
// Run automatically via the `predev` npm hook; safe to run by hand as well.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HEADER = '// Auto-generated by scripts/bump-version.mjs — do not edit by hand.'

/**
 * Pure version computation for testability.
 * @param {string | null} current previous version string, ignored for timestamp builds
 * @param {Date} [now] UTC date/time used for the yy.mm.dd.hhmm version
 * @returns {string} version in yy.mm.dd.hhmm format
 */
export function nextVersion(current, now = new Date()) {
  const yy = String(now.getUTCFullYear() % 100).padStart(2, '0')
  const mm = String(now.getUTCMonth() + 1).padStart(2, '0')
  const dd = String(now.getUTCDate()).padStart(2, '0')
  const hh = String(now.getUTCHours()).padStart(2, '0')
  const min = String(now.getUTCMinutes()).padStart(2, '0')
  return `${yy}.${mm}.${dd}.${hh}${min}`
}

const scriptPath = fileURLToPath(import.meta.url)
const versionFile = resolve(dirname(scriptPath), '../app/data/app-version.ts')

function main() {
  let current = null
  try {
    const existing = readFileSync(versionFile, 'utf8')
    const found = existing.match(/APP_VERSION\s*=\s*['"]([^'"]+)['"]/)
    current = found ? found[1] : null
  } catch {
    current = null
  }
  const next = nextVersion(current, new Date())
  mkdirSync(dirname(versionFile), { recursive: true })
  writeFileSync(versionFile, `${HEADER}\nexport const APP_VERSION = '${next}'\n`)
  console.log(`APP_VERSION=${next}`)
}

if (process.argv[1] && resolve(process.argv[1]) === scriptPath) {
  main()
}
