// Stamps the footer application version (yy.mm.build) using the local date and an incrementing counter.
// Run automatically via the `predev` npm hook; safe to run by hand as well.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HEADER = '// Auto-generated by scripts/bump-version.mjs — do not edit by hand.'

/**
 * Pure version computation for testability.
 * @param {string | null} current previous version string, if any
 * @param {Date} [now] local date used for the yy.mm prefix
 * @returns {string} version in yy.mm.build format
 */
export function nextVersion(current, now = new Date()) {
  const yy = String(now.getFullYear() % 100).padStart(2, '0')
  const mm = String(now.getMonth() + 1).padStart(2, '0')
  const match = typeof current === 'string' ? current.trim().match(/^(\d{2})\.(\d{2})\.(\d+)$/) : null
  if (!match) {
    return `${yy}.${mm}.1`
  }
  const [, curYy, curMm, curBuild] = match
  if (curYy === yy && curMm === mm) {
    return `${yy}.${mm}.${Number(curBuild) + 1}`
  }
  return `${yy}.${mm}.1`
}

const scriptPath = fileURLToPath(import.meta.url)
const versionFile = resolve(dirname(scriptPath), '../app/data/app-version.ts')

function main() {
  let current = null
  try {
    const existing = readFileSync(versionFile, 'utf8')
    const found = existing.match(/APP_VERSION\s*=\s*['"]([^'"]+)['"]/)
    current = found ? found[1] : null
  } catch {
    current = null
  }
  const next = nextVersion(current, new Date())
  mkdirSync(dirname(versionFile), { recursive: true })
  writeFileSync(versionFile, `${HEADER}\nexport const APP_VERSION = '${next}'\n`)
  console.log(`APP_VERSION=${next}`)
}

if (process.argv[1] && resolve(process.argv[1]) === scriptPath) {
  main()
}
